### ISSUE TITLE
Unable to open Here WeGo map in Android using LaunchNavigator 

### ISSUE THREAD

**Issue by DhruvSingh50** [dpa99c/phonegap-launch-navigator-example#11] opened 2019-01-28 08:56 UTC
I'm having problem with opening Here Map in Android ( It is working fine for iOS ).

```
Ionic -v : 3.20.0
node -v : 6.9.1
npm -v  : 5.6.0
cordova -v : 8.0.0`
```

```
launchNavigatorPopup(myAddress) {
this.launchNavigator.navigate(myAddress,
      {
        appSelection: {
          list: [
            this.launchNavigator.APP.GOOGLE_MAPS,
            this.launchNavigator.APP.HERE_MAPS
          ]
        }
      })
}
```
Note: myAddress is string type.

On clicking Here Maps nothing is happening. This code is working fine with Google maps (both iOS and Android) but with Here maps, it is not working on android devices.  

![screenshot_20190128-140306_01_01](https://user-images.githubusercontent.com/16085756/51823899-bbdb5400-2306-11e9-8beb-958f06a19055.png)

**Comment by dpa99c** [comment] 2019-01-29 09:54
Duplicate of https://github.com/dpa99c/phonegap-launch-navigator/issues/211

**Closed by dpa99c** 2019-01-29 09:54 UTC

**Comment by Ajaygply** [comment] 2022-01-04 13:20
did anyone get the solution for this?
launch navigator in android 11
